### ISSUE TITLE
Flexible installer with different paths for any environnement

### ISSUE THREAD

**Issue by damirius** [Puzzlout/CloudDeploy#2]

**Comment by WebDevJL** [comment]
@damirius can you document the usage here? Thanks.

**Comment by WebDevJL** [comment]
@damirius 

I am trying to generalize the installers so we don't have a version per server (which is already a lot!). It is found in the folder "global" in TrekToursInstaller and the API and flyer install scripts are those without any suffix.

The goal is to at least make it work local and liquid web.
A param would be the server of installation, e.g. local, lw (for LiquidWeb), or any other if we change server.

I tried on local and it works.
On LiquidWeb, not yet.

I also added on the flyer installer a check to skip bower install (see https://github.com/Puzzlout/CloudDeploy/blob/master/Projects/TrekTours/Flyer/install.sh).

Let me know if I've missed a detail. Thanks.
